#325 Serialization Exception
sngular/kloadgen pull request #328
Opened 2023-01-17 14:18 UTC by AdrianLagarteraSngular

**Why:**
This PR was created to resolve a problem related with the serialization on the `Avro Schemas`, the problem was related to Union types, which cannot fill the given schema properly.

**Technical Info:**
The main problem to solve this bug was to understand the way the algorithm assigns the data to our Schema, so to solve it I simply added a method to return the `Map` information that has the content of our previous generation.

**Points of Interest:**
Added a test with a reverse order in the schema to test if work in that way too.

2023-01-18 07:27 UTC, dianaGomezGar approved these changes

2023-01-19 07:57 UTC, mseijasm requested changes
You should change the pom version

2023-01-19 10:50 UTC, RaulBejaranoSngular approved these changes

2023-01-19 11:23 UTC, mseijasm approved these changes

2023-01-19 18:17 UTC, RaulBejaranoSngular approved these changes

2023-01-20 07:50 UTC, merged